export const USER_CHANGED_SUCCESS = "USER_CHANGED_SUCCESS";
export const LOAD_USER_ORDERS_SUCCESS = "LOAD_USER_ORDERS_SUCCESS";
export const CREATE_USER_ORDER_SUCCESS = "CREATE_USER_ORDER_SUCCESS";

export const ADMIN_CHANGED_SUCCESS = "ADMIN_CHANGED_SUCCESS";
export const LOAD_ALL_USERS_ORDERS_SUCCESS = "LOAD_ALL_USERS_ORDERS_SUCCESS";

